Add test.py to run script

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,7 +1,6 @@
 #!/bin/sh
 
 # All paths relative to this script
-
 cd "$(dirname "$0")"
 
 cfgstr="# KEYS
@@ -31,7 +30,15 @@ if ! [ -d "$VENV_DIR" ]; then
     python3 -m venv "$VENV_DIR"
 fi
 
-source .venv/bin/activate
+source "$VENV_DIR/bin/activate"
+echo "Upgrading pip..."
 python3 -m pip install -q --upgrade pip
+echo "Installing required modules..."
 python3 -m pip install -q -r src/requirements.txt
-python3 src/app.py
+
+echo "Running tests..."
+python3 src/tests/test.py
+if [ $? -eq 0 ]; then
+    echo "All tests passed, starting app"
+    python3 src/app.py
+fi
